version: '3.8'

services:
  autohome:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autohome_container
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && python app/autohome.py"
    environment:
      - PYTHONUNBUFFERED=1

  dcd:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dcd_container
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && python app/dcd.py"
    environment:
      - PYTHONUNBUFFERED=1
